# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College_Basic_Detail',
            fields=[
                ('collegeId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('courses', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='College_Placement_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalStudents', models.IntegerField()),
                ('placedStudents', models.IntegerField()),
                ('averageSalary', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('collegeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.College_Basic_Detail')),
            ],
        ),
    ]
