# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college_placement_detail',
            old_name='collegeId',
            new_name='college',
        ),
    ]
