# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-06 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
