# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-06 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0002_auto_20180807_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='entrannce_exam',
            new_name='entrance_exam',
        ),
    ]
