# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0003_auto_20180807_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entrance_exam',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
