# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-12 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0004_auto_20180810_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
