# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0006_auto_20180813_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Authentication',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('role', models.CharField(max_length=5)),
                ('date_of_birth', models.DateField(default=b'2018-08-20')),
                ('gender', models.CharField(default='NA', max_length=6)),
                ('school', models.CharField(default='NA', max_length=100)),
                ('city', models.CharField(default='NA', max_length=30)),
                ('state', models.CharField(default='NA', max_length=30)),
                ('father_name', models.CharField(default='NA', max_length=100)),
                ('father_mobile', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
