# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0007_auto_20180820_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='date_of_birth',
            field=models.DateField(default=b'2018-08-22'),
        ),
    ]
