# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0008_auto_20180822_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='date_of_birth',
            field=models.DateField(default=b'2018-08-25'),
        ),
    ]
