# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_user',
            name='student_id',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
