# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20180810_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_user',
            name='current_timestamp',
        ),
        migrations.RemoveField(
            model_name='current_user',
            name='student_id',
        ),
    ]
