# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-12 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20180810_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Current_User',
        ),
    ]
