# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=100)),
                ('collegeCity', models.CharField(max_length=100)),
                ('collegeState', models.CharField(max_length=100)),
                ('totalStudent', models.IntegerField(default=0)),
                ('placedStudent', models.IntegerField(default=0)),
                ('tuitionFee', models.IntegerField(default=0)),
            ],
        ),
    ]
