# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
